name: tea_estate_app
description: Tea Estate Manager app
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.0.0
  uuid: ^3.0.7
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
